/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/components/EscanerPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/components/formulario`; params?: Router.UnknownInputParams; } | { pathname: `/components/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/components/PresentacionPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/src/EscanerPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/src/formulario`; params?: Router.UnknownInputParams; } | { pathname: `/src/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/src/PresentacionPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EscanerPantalla`; params?: Router.UnknownOutputParams; } | { pathname: `/components/formulario`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Inicio`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PresentacionPantalla`; params?: Router.UnknownOutputParams; } | { pathname: `/src/EscanerPantalla`; params?: Router.UnknownOutputParams; } | { pathname: `/src/formulario`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Inicio`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PresentacionPantalla`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/App${`?${string}` | `#${string}` | ''}` | `/components/EscanerPantalla${`?${string}` | `#${string}` | ''}` | `/components/formulario${`?${string}` | `#${string}` | ''}` | `/components/Inicio${`?${string}` | `#${string}` | ''}` | `/components/PresentacionPantalla${`?${string}` | `#${string}` | ''}` | `/src/EscanerPantalla${`?${string}` | `#${string}` | ''}` | `/src/formulario${`?${string}` | `#${string}` | ''}` | `/src/Inicio${`?${string}` | `#${string}` | ''}` | `/src/PresentacionPantalla${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/components/EscanerPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/components/formulario`; params?: Router.UnknownInputParams; } | { pathname: `/components/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/components/PresentacionPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/src/EscanerPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/src/formulario`; params?: Router.UnknownInputParams; } | { pathname: `/src/Inicio`; params?: Router.UnknownInputParams; } | { pathname: `/src/PresentacionPantalla`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
